### ISSUE TITLE
Activation not possible

### ISSUE THREAD

**Issue by animaux** [pointybeard/cron#1]
When trying to activate the cron extension in Symphony `2.6.3` I get the following error:

`[03-Nov-2015 13:55:12 Europe/Berlin] PHP Parse error:  syntax error, unexpected '[' in /…/extensions/cron/extension.driver.php on line 10`

**Comment by animaux** [comment]
Running in MAMP `PHP 5.3.29`

**Comment by animaux** [comment]
@brendo pointed me to `PHP 5.3.x` as the issue. So maybe `5.4.x` should be mentioned as a requirement.

**Comment by pointybeard** [comment]
Right. I'll push a fix for this. Thanks for the bug report.
