### ISSUE TITLE
Autoload.php error

### ISSUE THREAD

**Issue by Manaus** [pointybeard/cron#2]
Hello,  
I'm getting this error on activating the extension: 

```
include(/Users/myuser/Sites/mywebsite/extensions/cron/vendor/autoload.php): failed to open stream: No such file or directory
```

Thanks!

**Comment by pointybeard** [comment]
@Manaus this extension uses the Composer autoloader to load its libraries. You will need to run the command `composer update` from within the Cron extension folder. I will make this clearer in the readme. Thanks for letting me know and please let me know if that solves the issue.

**Comment by pointybeard** [comment]
@Manaus I have included the `vendor/` folder in the code base. It adds the autoloader, which means you do not need to run the `composer update` command. I tested it locally and appears to be working find. Please let me know if it works for you.

**Comment by Manaus** [comment]
Yes the extension seems to perform well! 
Thanks!
